### ISSUE TITLE
Order of keys in translated YAML file is corrupted

### ISSUE THREAD

**Issue by plinyar** [gitlocalize/feedback#25]
After I translated english yml file into, say, french, and compared the two result files, the order if keys in french version was competely different, and I cannot comprehend (at the level of these two files) what and how is translated.
The keys should be in the same positions in the result files, so that we can compare them by, say Beyond Compare
We consider this requirement is essential.

**Comment by chikathreesix** [comment]
Hi @plinyar, thank you for reporting an issue. We acknowledged this and will work on this next week. I will let you know once it's fixed.

**Comment by sotayamashita** [comment]
@plinyar we are still working. We appreciate your patience

**Comment by plinyar** [comment]
Thanks for your updates!!!

Kind wishes,
  Roman Koreshkov

**Comment by ivan-nginx** [comment]
I got same issue here and will try to detail explain it:

1. My `ru.yml` was 99% translated and only 1 string was no translated. So, i translate it and make pull request.
2. After compare changes i see this difference:

**Before translate** with 1 untranslated string:
```yml
title:
  archive: Архив
  category: Категория
  tag: Тэг
  schedule: Календарь

author: Автор

menu:
  home: Главная
  archives: Архив
  categories: Категории
  tags: Тэги
  about: О сайте
  search: Поиск
  schedule: Календарь
  sitemap: Карта сайта

sidebar:
  overview: Обзор
  toc: Содержание

post:
  created: Дата создания записи
  modified: Дата обновления записи
  sticky: Ссылка
  posted: Размещено
  in: в категории
  more: далее
  read_more: Читать полностью
  untitled: Без имени
  toc_empty: Эта запись без оглавления
  visitors: Просмотров
  wordcount: Кол-во слов в статье
  min2read: Время чтения в минутах
  totalcount: Общее кол-во слов в записях
  totaltime: Время чтения всего сайта
  copyright:
    author: Автор записи
    link: Ссылка на запись
    license_title: Информация об авторских правах
    license_content: 'Все записи на этом сайте защищены лицензией
      <a href="%s" rel="external nofollow" target="_blank">%s</a> если не указано дополнительно.'

page:
  totally: Всего
  tags: тэги

footer:
  powered: "Powered by %s"
  theme: Theme

counter:
  tag_cloud:
    zero: Нет тэгов.
    one: 1 тэг.
    two: "%d тэга всего."
    three: "%d тэга всего."
    four: "%d тэга всего."
    other: "%d тэгов всего."

  categories:
    zero: Нет категорий.
    one: 1 категория.
    two: "%d категории всего."
    three: "%d категории всего."
    four: "%d категории всего."
    other: "%d категорий всего."

  archive_posts:
    zero: Нет записей.
    one: 1 запись.
    two: "%d записи всего."
    three: "%d записи всего."
    four: "%d записи всего."
    other: "%d записей всего."

state:
  posts: Архив
  pages: Страницы
  tags: Тэги
  categories: Категории

search:
  placeholder: Поиск...

cheers:
  um: Эм..
  ok: OK
  nice: Неплохо
  good: Хорошо
  great: Замечательно
  excellent: Великолепно

keep_on: Продолжаю писать.

symbol:
  comma: ', '
  period: '. '
  colon: ':'

reward:
  donate: Донат
  wechatpay: WeChat Pay
  alipay: Alipay
  bitcoin: Bitcoin
```

**After translate** via GL:
```yml
---
author: Автор
cheers:
  excellent: Великолепно
  good: Хорошо
  great: Замечательно
  nice: Неплохо
  ok: OK
  um: Эм..
counter:
  archive_posts:
    four: "%d записи всего."
    one: 1 запись.
    other: "%d записей всего."
    three: "%d записи всего."
    two: "%d записи всего."
    zero: Нет записей.
  categories:
    four: "%d категории всего."
    one: 1 категория.
    other: "%d категорий всего."
    three: "%d категории всего."
    two: "%d категории всего."
    zero: Нет категорий.
  tag_cloud:
    four: "%d тэга всего."
    one: 1 тэг.
    other: "%d тэгов всего."
    three: "%d тэга всего."
    two: "%d тэга всего."
    zero: Нет тэгов.
footer:
  powered: Powered by %s
  theme: Theme
keep_on: Продолжаю писать.
menu:
  about: О сайте
  archives: Архив
  categories: Категории
  home: Главная
  schedule: Календарь
  search: Поиск
  sitemap: Карта сайта
  tags: Тэги
  commonweal: Страница 404
page:
  tags: тэги
  totally: Всего
post:
  copyright:
    author: Автор записи
    license_content: Все записи на этом сайте защищены лицензией <a href="%s" rel="external
      nofollow" target="_blank">%s</a> если не указано дополнительно.
    license_title: Информация об авторских правах
    link: Ссылка на запись
  created: Дата создания записи
  in: в категории
  min2read: Время чтения в минутах
  modified: Дата обновления записи
  more: далее
  posted: Размещено
  read_more: Читать полностью
  sticky: Ссылка
  toc_empty: Эта запись без оглавления
  totalcount: Общее кол-во слов в записях
  totaltime: Время чтения всего сайта
  untitled: Без имени
  visitors: Просмотров
  wordcount: Кол-во слов в статье
reward:
  alipay: Alipay
  bitcoin: Bitcoin
  donate: Донат
  wechatpay: WeChat Pay
search:
  placeholder: Поиск...
sidebar:
  overview: Обзор
  toc: Содержание
state:
  categories: Категории
  pages: Страницы
  posts: Архив
  tags: Тэги
symbol:
  colon: ":"
  comma: ", "
  period: ". "
title:
  archive: Архив
  category: Категория
  schedule: Календарь
  tag: Тэг
```

So, as u see there is 3 bugs:

1. At the top of file `---` string was added, but in original file this string is not exists.
2. All strings sorted by alphabetically and it is hard for future maintenanse languages: maintainers will search needed locations where new string will be added.
3. All spaces cutted out and this is brake all manual formation style.

***

I suggest at least to add some option in GL account config which will prevent this hard breaking formation from original files. Just something like checkbox: «Stay originlal formatting style».
