### ISSUE TITLE
Add ability to specify expresssions to be excluded from auto-translate using RegExp

### ISSUE THREAD

**Issue by agektmr** [gitlocalize/feedback#67]
### Summary

I'd like to have some expressions to be excluded from auto-translation. 
For example, in our project, paragraphs starting with `Note:` are converted into a table with colored background when it's built.
https://developers.google.com/web/resources/markdown-syntax#callouts

### Repository URL

https://github.com/google/WebFundamentals/

### What is the current *bug* behavior?

`Note:` being translated to `注：` in Japanese, for example.

### What is the expected *correct* behavior?

`Note:` being excluded from translation and stay as the same `Note:`.

**Comment by svasilenkov** [comment]
Wa have implemented this in .gitlocalize.yml configuration file. Suggested configuration for Google Web Fundamentals repository:

```
pretranslate:  
  segments:
    ignore_patterns:
    - "{# wf_(?!featured_snippet).*#}"
    - "^(Note|Caution|Warning|Success|Key Point|Key Term|Objective|Dogfood): "
    - "{:.*}"
    - "{%.*%}"
```
